<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 track-lines.glb --transform
-->

<script>
  import { Group } from 'three'
  import { T, Three } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const { gltf } = useGltf('/track-lines-transformed.glb', { useDraco: true })
</script>

{#if $gltf}
  <Three type={ref} {...$$restProps}>
    <T.Mesh geometry={$gltf.nodes.Lines.geometry} material={$gltf.nodes.Lines.material} />

    <slot {ref} />
  </Three>
{/if}
